apiVersion: apps/v1
kind: Deployment
metadata:
  name: hits-api
  labels:
    app: hits-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hits-api
  template:
    metadata:
      labels:
        app: hits-api
    spec:
      containers:
        - name: api
          image: hits-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: APP_ENV
              value: "k8s"
            - name: GREETING
              value: "Hello from K8s (HITS)"
            - name: VERSION
              value: "0.1.0"
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
