apiVersion: v1
kind: Service
metadata:
  name: hits-api
  labels:
    app: hits-api
spec:
  selector:
    app: hits-api
  type: NodePort
  ports:
    - name: http
      port: 5001
      targetPort: 5001
      nodePort: 30081
