apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: demo
spec:
  replicas: 1
  selector: { matchLabels: { app: vault } }
  template:
    metadata: { labels: { app: vault } }
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.17
        args: ["server", "-dev", "-dev-listen-address=0.0.0.0:8200", "-dev-root-token-id=root"]
        ports: [ { containerPort: 8200 } ]
---
apiVersion: v1
kind: Service
metadata: { name: vault, namespace: demo }
spec:
  selector: { app: vault }
  ports: [ { name: http, port: 8200, targetPort: 8200 } ]
---
apiVersion: batch/v1
kind: Job
metadata: { name: vault-seed, namespace: demo }
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: seed
        image: curlimages/curl:8.8.0
        env:
        - { name: VAULT_ADDR, value: "http://vault.demo.svc.cluster.local:8200" }
        - { name: VAULT_TOKEN, value: "root" }
        command: ["sh","-lc"]
        args:
        - |
          curl -sS -H "X-Vault-Token: $VAULT_TOKEN" -H "Content-Type: application/json" \
          -d '{"data":{"message":"Hello from Vault!"}}' "$VAULT_ADDR/v1/secret/data/app"
